home/urls.py
from django.conf.urls import patterns, url
from home import views

urlpatterns = patterns('', 
        url(r'^$', views.home, name='home'),
        url(r'about/', views.about, name='about'), # this is a description about my whole website
        )

myWeb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
import blog, home

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myWeb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'grappelli/', include('grappelli.urls')),
    url(r'^$', 'home.views.home', name="home"),  # The website homepage
    url(r'^home/', include('home.urls', namespace="home")), # The website homepage
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^vpn/', include('vpn.urls', namespace="vpn")),
    url(r'^admin/', include(admin.site.urls)),
)
if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Any pattern states that for any file requested with a URL starting with media/, the request will be passed to the django.views.static view.
# This views handles the dispatching of upload media files for you.
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}),
    )

vpn/urls.py
from django.conf.urls import patterns, url
from vpn import views


urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^register/', views.register, name='register'),
        url(r'^logout/', views.user_logout, name='logout'),
        url(r'^login/', views.user_login, name='login'),
    )

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here
def home(request):
    context_dict = {
            'user':'shady'
            }
    return render(request, 'home/home.html', context_dict)
def about(request):
    context_dict = {
            'user':'shady'
            }
    return render(request, 'home/about.html', context_dict)

templates/home/about.html
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block title %}
    About
{% endblock %}

{% block custome_css %}
    <link href="{% static 'common/css/navbar.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/about.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    {% include 'home/navbar.html' %}
<div class="container">
    <div class="page-header">
        <h3 id="timeline">本站发展史</h3>
    </div>

    <ul class="timeline">
        
        <li>
          <div class="timeline-badge"><i class="glyphicon glyphicon-check"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">There is always a story</h4>
              <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> 2015-10-27 by shady via vim</small></p>
            </div>
            <div class="timeline-body">
                <p>At the very beginning, I was hoping to build a self-host blog for better learning. But after I met Django and Python, things change. I want to build a real website with database, and other wonderful technique. </p>
            </div>
          </div>
        </li>

        <li class="timeline-inverted">
          <div class="timeline-badge warning"><i class="glyphicon glyphicon-credit-card"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">The spirit of sharing</h4>
            </div>
            <div class="timeline-body">
                <p>Then things become clear to me, do the design, and plan the hack. Thanks to the spirit of sharing I found lots of wonderful open source code. Since I am a new fish in front end development. Due to the spirit of sharing, and great project like bootstrap, it make the life easier. This website begin to come to shape.</p>
            </div>
          </div>
        </li>

        <li>
          <div class="timeline-badge danger"><i class="glyphicon glyphicon-credit-card"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Mussum ipsum cacilds</h4>
            </div>
            <div class="timeline-body">
              <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
            </div>
          </div>
        </li>

        <li class="timeline-inverted">
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Mussum ipsum cacilds</h4>
            </div>
            <div class="timeline-body">
              <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
            </div>
          </div>
        </li>

        <li>
          <div class="timeline-badge info"><i class="glyphicon glyphicon-floppy-disk"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Mussum ipsum cacilds</h4>
            </div>
            <div class="timeline-body">
              <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
              <hr>
              <div class="btn-group">
                <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
                  <i class="glyphicon glyphicon-cog"></i> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                </ul>
              </div>
            </div>
          </div>
        </li>

        <li>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Mussum ipsum cacilds</h4>
            </div>
            <div class="timeline-body">
              <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
            </div>
          </div>
        </li>

        <li class="timeline-inverted">
          <div class="timeline-badge success"><i class="glyphicon glyphicon-thumbs-up"></i></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h4 class="timeline-title">Mussum ipsum cacilds</h4>
            </div>
            <div class="timeline-body">
              <p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>
            </div>
          </div>
        </li>
    </ul>
</div>

    {% include 'home/footer.html' %}
{% endblock %}

templates/home/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    {% block meta_icon %}
    {% endblock %}

    <title>{% block title %}{% endblock %}</title>

    <!-- Latest compiled and minified CSS -->
    <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous"-->
    <link href="{% static 'common/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

    {% block custome_css %}
    {% endblock %}
  </head>
<!-- NAVBAR
================================================== -->
  <body>

    {% block content %}
    {% endblock %}

    <!-- Using the CND and the local source file -->
    <script src="http://cdn.staticfile.org/jquery/2.1.1-rc2/jquery.min.js"></script>
    <!--script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script--> 
    <script>window.jQuery || document.write('<script src="{% static "common/js/jquery.min.js" %}">\x3C/script>')</script>
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="http://cdn.staticfile.org/twitter-bootstrap/3.3.1/js/bootstrap.min.js"> </script>
    <script> $.fn.modal || document.write('<script src="{% static "common/css/bootstrap.min.js" %}">\x3C/script>')</script>

    {% block custome_js %}
    {% endblock %}
  </body>
</html>

templates/home/carousel.html
{% load staticfiles %}
<!-- Carousel ================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img class="first-slide" src="{% static 'home/images/snail.jpg' %}" alt="First slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Example headline.</h1>
                    <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
                </div>
            </div>
        </div>

        <div class="item">
            <img class="second-slide" src="{% static 'home/images/mount.jpg' %}" alt="Second slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Another example headline.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                </div>
            </div>
        </div>

        <div class="item">
            <img class="third-slide" src="{% static 'home/images/road.jpg' %}" alt="Third slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>One more for good measure.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                </div>
            </div>
        </div>
    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>

    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div><!-- /.carousel -->

templates/home/feature.html
<!-- START THE FEATURETTES -->
{% load staticfiles %}
<!-- Divided this into four page in the website -->

<div class="section">
    <div class="container marketing">
        <hr class="featurette-divider">
        <div class="row featurette part1">
            <div class="col-md-7">
                <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
            </div>
           
            <div class="col-md-5">
                <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
            </div>
        </div>
    </div> <!-- End of the container -->
</div>

<div class="section">
    <div class="container marketing">
        <hr class="featurette-divider">
        <div class="whole center-block">
            <div class="row featurette part2">
                <div class="col-md-7 col-md-push-5">
                    <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
                    <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
                </div>

                <div class="col-md-5 col-md-pull-7">
                    <img class="featurette-image img-responsive center-block" src="{% static 'home/images/billbow.jpg'%}" alt="Generic placeholder image">
                </div>
            </div>
        </div>
    </div> <!-- End of the container -->
</div>


<div class="section">
    <div class="container marketing">
        <hr class="featurette-divider">
        <div class="row featurette part3">
            <div class="col-md-7">
                <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
            </div>

            <div class="col-md-5">
                <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
            </div>
        </div>
    </div>
</div>

<div class="section">
    <div class="container marketing">
        <hr class="featurette-divider">
        <div class="row featurette part1">
            <div class="col-md-7">
                <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
            </div>
           
            <div class="col-md-5">
                <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
            </div>
        </div>
    </div> <!-- End of the marketing container -->
    {% include 'home/footer.html' %}
</div>


<!-- /END THE FEATURETTES -->

templates/home/footer.html
<!-- FOOTER -->
<footer class="footer">
    <div class="container">
        <p class="pull-right" data-id="fullpage" style="font-size: 1.32em;">All of the buildings, all of those cars were once just a dream in somebody's head.</p>
        <p>&copy; 2015 Shady,. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </div>
</footer>

templates/home/home.html
<!DOCTYPE html>
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block meta_icon %}
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'common/images/favicon.ico' %}">
{% endblock %}
<!-- The page title -->

{% block title %}
    CodeFun
{% endblock %}

<!-- Adding customized css stylesheet to the base html -->
{% block custome_css %}
    <!-- Custom styles for this template -->
    <link href="{% static 'common/css/navbar.css' %}" rel="stylesheet">
    <link href="{% static 'common/css/sticky-footer.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'common/css/jquery.fullPage.css' %}" rel="stylesheet">
{% endblock%}

{% block custome_js %}
    <script type='text/javascript' src="{% static 'common/js/jquery.fullPage.min.js' %}"> </script>
    <script type='text/javascript' src="{% static 'common/js/startfullpage.js' %}"> </script> 
{% endblock%}

{% block content %}

    <div id="fullpage">    
        <div class="section">
        {% include 'home/navbar.html' %}
        {% include 'home/carousel.html' %}
        </div>
        <div class=section>
        {% include 'home/marketing.html' %}
        </div>
        <!-- Since the section had been divided into different pages, so the section cannot be here -->
        {% include 'home/feature.html' %}
    </div>
{% endblock %}

templates/home/marketing.html
<!-- Marketing messaging and featurettes ================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->
<!-- Three columns of text below the carousel -->
<div class="container marketing">
<div class="row">
    <div class="col-lg-4">
        <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->

    <div class="col-lg-4">
        <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
        <h2>Heading</h2>
        <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->

    <div class="col-lg-4">
        <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
</div><!-- /.row -->
<div class="row">
    <div class="col-lg-4">
        <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
</div>
</div>

templates/home/navbar.html
<div class="navbar-wrapper"> 
    <div class="container"> 
        <nav class="navbar navbar-inverse  navbar-fix-top"> <!-- static --> 
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home' %}">Carpe Diem</a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'home:home' %}"><!-- class="active" -->
                            <span class="glyphicon glyphicon-send" aria-hidden="true"> Home</span></a>
                        </li>
                        <li><a href="{% url 'blog:index' %}">
                            <span class="glyphicon glyphicon-bookmark" aria-hidden="true"> Blog</span></a>
                        </li>
                        <li><a href="{% url 'vpn:index' %}">
                            <span class="glyphicon glyphicon-leaf" aria-hidden="true"> VPN</span></a>
                        </li>
                        <li><a href="{% url 'home:about' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"> About</span></a>
                        </li>
                        <li><a href="rl 'home:contact' %}">
                            <span class="glyphicon glyphicon-envelope" aria-hidden="true"> Contact</span></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-tint" aria-hidden="true"> Dropdown</span> <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li class="dropdown-header">Nav header</li>
                                <li><a href="#">Separated link</a></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
  </div>
</div>