blog/urls.py
from django.conf.urls import patterns, url
from blog import views

urlpatterns = patterns('', 
        url(r'^$', views.index, name='index'),
        url(r'about/', views.about, name='aboutme'), # This is the bloig about me section
        url(r'^tags/(?P<tag_name_slug>[\w\-]+)/$', views.tags, name='tags'),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/(?P<post_title>[\w\-]+)/$', views.single_post, name='single_post'),
        )

myWeb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
import blog, home

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myWeb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'grappelli/', include('grappelli.urls')),
    url(r'^$', 'home.views.home', name="home"),  # The website homepage
    url(r'^home/', include('home.urls', namespace="home")), # The website homepage
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^vpn/', include('vpn.urls', namespace="vpn")),
    url(r'^admin/', include(admin.site.urls)),
)
if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Any pattern states that for any file requested with a URL starting with media/, the request will be passed to the django.views.static view.
# This views handles the dispatching of upload media files for you.
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}),
    )

vpn/urls.py
from django.conf.urls import patterns, url
from vpn import views


urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^register/', views.register, name='register'),
        url(r'^logout/', views.user_logout, name='logout'),
        url(r'^login/', views.user_login, name='login'),
    )

blog/models.py
from django.db import models
#from django.template.defaultfilters import slugify
from slugify import slugify

# Create your models here.
class Tag(models.Model):
    tag_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30, unique=True)
# Record the tag's frequence, add one when a post is related to that tag
    frequence = models.PositiveIntegerField(default=0)
    
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Tag, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Post(models.Model):
    # A primary key field will automatically be added to your model, if you don't specify.
    post_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50)
    content = models.TextField()
    abstract = models.CharField(max_length=300)
    publish_date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=20)
    # 0 stands for public
    # 1 stands private or draft
    POST_ATTRIBUTES = (
                ('PL', 'Public'),
                ('PT', 'Private'),
                ('RT', 'Reprint'),
                ('DE', 'Debatable'),
            )
    status = models.CharField(max_length=2, choices=POST_ATTRIBUTES,default='PL')
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveIntegerField(default=0)
    image_link = models.URLField(blank=True)
    category= models.ForeignKey('Category')
    tags = models.ManyToManyField(Tag)
    slug = models.SlugField(unique=True)


    def save(self, *args, **kwargs):
        # The post is first add, instead of update 
        if not self.post_id:
            category = Category.objects.get(pk = self.category_id)
            category.related_post += 1
            category.save()
#            tags = Tag.objects.filter(post__post_id = self.post_id)
#            for tag in tags:
#                tag.frequence += 1
#                tag.save()
#
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Category(models.Model):
    category_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, unique=True)
# Counting how many post are belong to the category 
    related_post = models.PositiveIntegerField(default=0)
    create_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    
    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from blog.models import Tag, Category, Post

# Create your views here.

# Create the home page of the blog
def index(request):
    context_dict = common()
    post_list = Post.objects.order_by('-publish_date')

    # Adding the category of the post, bundle the post object and the category object together.
    class Append_category():
        pass
    result = []
    for post in post_list:
        add_category = Append_category()
        add_category.post = post
# Retreive the category of the post(FK)
        add_category.category = Category.objects.get(pk=post.category_id)
        result.append(add_category)
    post_list = result

    paginator = Paginator(post_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context_dict['posts'] = posts
    return render(request, 'blog/index.html', context_dict)

# Return the Tags and the Categories
def common():
    # Create the tag cloud in the index page
    tag_list = Tag.objects.order_by('frequence')
    # List all the category in the side bar
    category_list = Category.objects.order_by('name')
    context_dict = {
            'tags': tag_list,
            'categories': category_list,
            }
    return context_dict


# Create a page for different categories
def category(request, category_name_slug):
# create a context dictionary which we can pass to the template rendering engine
    context_dict = common()
    try:
        # If we find a category name slug with the given name?
        # Otherwise the get() method raise a DoesNotExist exception
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category_name'] = category.name
        # Retrieve all the associated pages
        # Note that filter returns >= 1 model instance
        posts_list = Post.objects.filter(category__category_id=category.category_id)


        # Cannot find another good way to do this. Mark here for better improvement
# create another class that contain the result of the post query
# in order to add the tags field in the result
        class Append_tag():
            pass
        result = []
        for post in posts_list:
            add_tag = Append_tag()
# Add the tags object 
            add_tag.tags = Tag.objects.filter(post__post_id = post.post_id)
# add the original post object
            add_tag.post = post
            result.append(add_tag)
        
        context_dict['category'] = category
        posts_list = result

    except Category.DoesNotExist:
        return render(request, 'common/404.html')

    paginator = Paginator(posts_list, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
    # if the page is not an integer, deliver first page
        posts = paginator.page(1)
    except EmptyPage:
    # If page is out of range, deliver last page of results
        posts = paginator.page(paginator.num_pages)

    context_dict['posts'] = posts
    return render(request, 'blog/category.html', context_dict)

def tags(request, tag_name_slug):
    context_dict = common()
    try:
        tag = Tag.objects.get(slug=tag_name_slug)
        posts_list = Post.objects.filter(tags__tag_id = tag.tag_id)
        context_dict['tag'] = tag
    except (Tag.DoesNotExist, Post.DoesNotExist):
        pass
    class Append_category():
        pass

    result = []
    for post in posts_list:
        add_category = Append_category()
        add_category.category = Category.objects.get(pk = post.category_id)
        add_category.tags = Tag.objects.filter(post__post_id=post.post_id)
        add_category.post = post
        result.append(add_category)

    posts_list = result
    paginator = Paginator(posts_list, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
    # if the page is not an integer, deliver first page
        posts = paginator.page(1)
    except EmptyPage:
    # If page is out of range, deliver last page of results
        posts = paginator.page(paginator.num_pages)

    context_dict['posts'] = posts
    return render(request, 'blog/tags.html', context_dict)

def single_post(request, category_name_slug, post_title):
    context_dict = common()
    try:
        post = Post.objects.get(slug=post_title)
        category = Category.objects.get(slug=category_name_slug)
        post_list = Post.objects.filter(category__category_id=category.category_id).order_by('post_id')
    except (Post.DoesNotExist, Category.DoesNotExist):
        pass#404 here
# To check if there are next page or previus page. Not related to the category
# Turn the queryset into a list, in order to use the index method.
    post_list = list(post_list)
    condition = {}
    prev, next = True, True
    if post.post_id == post_list[0].post_id:
        prev = False
    if post.post_id == post_list[len(post_list)-1].post_id:
        next = False
    if prev:
        condition['has_pre'] = prev
        condition['pre_slug'] = post_list[post_list.index(post)-1].slug
    if next:
        condition['has_next'] = next
        condition['next_slug'] = post_list[post_list.index(post)+1].slug

    context_dict['category'] = category_name_slug
    context_dict['condition'] = condition
    context_dict['post'] = post
    return render(request, 'blog/post.html', context_dict)

    
def about(request):
	return render(request, 'blog/resume.html')

templates/blog/aside.html
{% load staticfiles %}
<!--//Off Canvas//-->
<aside class="sp-off-canvas">
<div class="sp-off-canvas-inner">
  <!--//Header//-->
  <header class="sp-header">
      <button class="sp-close-btn"><i class="sp-icon fa fa-power-off fa-3x"></i></button>
    <img src="{% static 'blog/images/vetta.jpg' %}" alt="">
    <div class="sp-text">
        <h2 class="sp-brand"><a href="{% url 'blog:index' %}">Vendetta</a></h2>
    <!-- Appear above the logo -->
    <!--p class="sp-tagline">Illusion of Coincidence</p--> 
    </div>
      <p class="sp-tagline">Illusion of Coincidence</p>
  </header> <!--//End Header-->

  <!--//Search//-->
  <div class="sp-widget">
    <form class="sp-search">
      <input type="search" placeholder="Search">
      <button class="sp-search-btn" type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div> <!--//End Search-->

  <!--//Menu//-->
  <div class="sp-widget sp-menu">
        <div class="list-group">
            <ul class="sp-nav">
                <li><a class="list-group-item" href="{% url 'home:home' %}"><i class="fa fa-home fa-fw"></i>&nbsp;主页</a></li>
                <li><a class="list-group-item" href="{% url 'blog:index' %}"><i class="fa fa-rss fa-fw"></i>&nbsp;博客</a></li>
                <li><a class="list-group-item" href="../blog/time.html"><i class="fa fa-paper-plane-o fa-fw"></i>&nbsp;时间线</a></li>
				<li><a class="list-group-item" href="{% url 'blog:aboutme' %}"><i class="fa fa-envelope fa-fw"></i>&nbsp;关于 & 联系</a></li>
                <li><a class="list-group-item" href="../blog/link.html"><i class="fa fa-link fa-fw"></i>&nbsp;友链</a></li>
            </ul>
        </div>
  </div> <!--//End Menu-->
  <!--//Categories//-->
  <div class="sp-widget sp-categories">
      <h3 class="sp-widget-title"><i class="fa fa-bookmark-o fa-2x"></i>&nbsp分类</h3>

    <ul class="sp-nav sp-category">
        {% if categories %}
            {% for category in categories %}
            <li><a href="{% url 'blog:category' category.slug %}">{{ category.name }} <span>({{ category.related_post }})</span></a></li>
            {% endfor %}
        {% else %}
        <li><a href="#">懒人日记<span>(100^100)</span></a></li> <!-- 404 pages -->
        {% endif %}
    </ul>
  </div> <!--//End Categories-->

  <!--// Tags //-->
  <div class="sp-widget sp-tags">
      <h4 class="sp-widget-title"><i class="fa fa-tags fa-2x"></i>&nbsp标签</h4>
    <div class="sp-tag-cloud">
        {% if tags %}
            {% for tag in tags %}
            <a href="{% url 'blog:tags' tag.slug %}">{{ tag.name }} </a>
            {% endfor %}
        {% else %}
        <a href="#">懒人一个</a> <!-- The 404 Page -->
        {% endif %}
    </div>
  </div> <!-- //End Tags -->

  <div class="sp-misc">
    <a class="sp-top" href="#top"><i class="fa fa-rocket fa-2x"></i> Back to Top</a>
  </div>

</div>
</aside> <!--//End Off Canvas-->

templates/blog/category.html
{% extends 'blog/blog_base.html' %}       
{% load staticfiles %}
{% block update %}
<!-- Main Content -->
<div class="container"><!-- Override the css of the container in bootstrap -->
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <h1 class="category-name"><i class="fa-icon fa fa-cubes fa-2x"></i>Category: {{ category_name }}</h1>
            <!-- 打印对应的文章信息 -->
            {% if category %}
                {% if posts %}
                    {% for bundle in posts %}
                        <div class="row">
                    <div class="col-xs-4 col-sm-4">
                        <img src="http://7xo4sa.com1.z0.glb.clouddn.com/owl.jpg" class="infor img-circle" alt="Loading..." style="width: 100px;  height: 100px;" />
                        <span class="infor"><i class="fa fa-calendar-check-o fa-2x"></i> 发表时间：2014-12-02 </span>
                    </div>
                    <div class ="col-xs-8 col-sm-6">
                        <!--
                        <a class="post-title" href="../blog/category/{{ category }}/{{ bundle.post.slug }}/" data-toggle="tooltip" data-placement="top" title="点击查看该文章～" >    {{ bundle.post.title }} </a> -->
    <a class="post-title" href="{% url 'blog:single_post' category bundle.post.slug  %}" data-toggle="tooltip" data-placement="top" title="点击查看该文章～" >    {{ bundle.post.title }} </a>
                        <div class="blog-infor pull right">
                            <span><i class="fa fa-tags"></i> 标签: 
                                {% for tag in bundle.tags %}
                                    <span><a href="{% url 'blog:tags' tag.slug %}">{{ tag.name }} |  </a></span>
                                {% endfor %}
                            </span>
                            <span><i class="fa fa-folder"></i>  分类:<a href="{% url 'blog:category' category.slug %}"> {{ category }}</a></span>
                        </div>
                    </div>
                    </div>
                    <p align="right">
                        <span><i class="fa fa-eye"></i> 阅读<span class="badge">{{ bundle.post.views }} </span>
                        <span><i class="fa fa-thumbs-up"></i> 赞<span class="badge">{{ bundle.post.likes }} </span>
                        <span><i class="fa fa-comments"></i> 评论<span class="badge"> 0 </span> <!-- the comment function is not implemented yet -->
                  </p>
                  <hr/>
                    {% endfor %}
                {% endif %}
            {% endif %}
    <!-- -Doing some significant change-->
           
            <!-- 实现分页显示 -->
            <div class="pagination">
                <span class="step-links">
                        {% if posts.has_previous %}
                            <a class="sp-prev" href="?page={{ posts.previous_page_number }}"><i class="fa fa-caret-square-o-left"></i> 上一页</a>
                        {% endif %}

                        <span class="current">
                            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                        </span>

                        {% if posts.has_next %}
                            <a class="sp-next" href="?page={{ posts.next_page_number }}">下一页 <i class="fa fa-caret-square-o-right"></i></a>
                        {% endif %}
                </span>
            </div><!-- End of the pagination -->
        </div> 
    </div> <!-- End of the container -->
</div>
{% endblock %}

templates/blog/footer.html
<!--//Footer//-->
<footer class="sp-footer">
  <div class="sp-widget-area">
    <div class="sp-container sp-clearfix">
      <div class="sp-box">
        <!--//Widget//-->
        <div class="sp-widget sp-about">
          <h3 class="sp-title">关于本站</h3>
          <div class="sp-desc">
              <p>个人博客， 记录生活点滴...</p>
            <a href="../blog/about.html">知道更多</a>
          </div>
        </div> <!--//End Widget-->
        <!--//Widget//-->
        <div class="sp-widget sp-subscribe">
            <h3 class="sp-title">订阅</h3>

          <p>This is the Subscribe Box Widget. Lorem ipsum dolor sit amet elit.</p>
          <form class="sp-subscribe-form">
            <input type="email" placeholder="Enter your e-mail">
            <button class="button button-default" type="submit">订阅</button>
          </form>
        </div> <!--//End Widget-->
        <!--//Widget//-->
        <div class="sp-widget sp-social-links">
          <h3 class="sp-title">联系我:</h3>
          <ul class="sp-social-link">
            <li><a class="github" href="https://github.com/Root-shady" data-toggle="tooltip" data-replacement="top" title="Github" ><i class="fa fa-github"></i></a></li>
            <li><a class="stackoverflow" href="http://stackoverflow.com/users/3628275/shady" data-toggle="tooltip" data-replacement="top" title="Stackoverflow"><i class="fa fa-stack-overflow"></i></a></li>
            <li><a class="mail" href="mailto:darkercookies@gmail.com" data-toggle="tooltip" data-replacement="top" title="Gmail"><i class="fa fa-envelope-o"></i></a></li>
            <li><a class="rss" href="#" data-toggle="tooltip" data-replacement="top" title="RSS"><i class="fa fa-rss"></i></a></li>
            <li><a class="facebook" href="" data-toggle="tooltip" data-replacement="top" title="Facebook"><i class="fa fa-facebook"></i></a></li>
            <li><a class="weixin" href="#" data-toggle="tooltip" data-replacement="top" title="Weixin"><i class="fa fa-weixin"></i></a></li>
          </ul>
        </div> <!--//End Widget-->
      </div>
    </div>
  </div>

  <div class="sp-footer-bottom sp-clearfix">
    <div class="sp-container">
      <!--//Copyright//-->
      <p class="sp-copyright">Copyright &copy; 2015 &mdash; <a href="../">CopyCat</a> Powered By <a href="https://www.djangoproject.com/">Django</a></p> <!--//End Copyright-->
      <!--//Footer Nav//-->
      <ul class="sp-footer-nav">
          <li><a href="{% url 'home:home' %}"><i class="fa fa-home fa-2x"></i>主页</a></li>
          <li><a href="{% url 'blog:index' %}"><i class="fa fa-rss fa-2x"></i>博客</a></li>
          <li><a href="#top"><i class="fa fa-rocket fa-2x"></i>顶部</a></li>
      </ul> <!--//End Footer Nav-->
    </div>
  </div>
</footer> <!--//End Footer-->

templates/blog/post.html
{% extends 'blog/blog_base.html' %}
{% load staticfiles %}
{% load markdown_deux_tags %}

{% block update %}
<!--//Post//-->
<article class="sp-post">
    <div class="row" >
        <div class="sp-post-content">
            <div class="sp-container">
                <div class="sp-post-desc">
                    <header class="sp-post-header">
                        <div class="sp-meta">
                            <span><a href="{% url 'blog:category' category %}">{{ category }}</a></span> 
                            <span>{{ post.publish_date }}</span>
                        </div>
                        <a href="."><h2 class="sp-post-title">{{ post.title }}</h2></a>
                            <div class="sp-post-info sp-clearfix">
                                <div class="sp-post-meta">
                                    <img class="sp-avatar" src="http://7xo4sa.com1.z0.glb.clouddn.com/owl.jpg" alt="">
                                    <p class="sp-author-name"><i class="fa fa-pencil"></i> by:<a href="/blog/about.html">{{ post.author }}</a></p>
                                    <p class="sp-comment-count"> <i class="fa fa-tripadvisor"></i> views: {{ post.views }} </p>
                                    <hr class="sp-separator">
                                </div>
                                <div class="sp-share-this">
                                    <p class="sp-meta-title"> FollowMe:</p>
                                    <p class="sp-share-list">
                                    <a class="facebook" href="#" data-toggle="tooltip" data-replacement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
                                    <a class="weixin" href="#" data-toggle="tooltip" data-replacement="top" title="Weixin"><i class="fa fa-weixin"></i></a>
                                    <a class="mail" href="#" data-toggle="tooltip" data-replacement="top" title="Gmail"><i class="fa fa-envelope"></i></a>
                                    <a class="github" href="#" data-toggle="tooltip" data-replacement="top" title="Github"><i class="fa fa-github"></i></a>
                                    </p>
                                </div>
                            </div>
                    </header>

                <div class="sp-entry-content">
                    <!-- The whole content -->
                    {{ post.content | markdown:"trusted" }}
                </div>
            </div>
        </div>
    </div>
</article> <!--//End Post-->
            <!-- pagination here -->
            <div class="sp-pagination">
                <div class="sp-container">
                    <div class="sp-pagination-inner sp-clearfix">
                        {% if condition.has_pre %}
                            <a class="sp-prev" href="{% url 'blog:single_post' category condition.pre_slug %}"><i class="fa fa-caret-square-o-left"></i>上一页</a>
                        {% endif %}
                        {% if category %}
                            <a class="sp-category" href="{% url 'blog:category' category %}"><i class="fa fa-tree"></i>分类目录</a>
                        {% endif %}
                        {% if condition.has_next %}
                            <a class="sp-next" href="{% url 'blog:single_post' category condition.next_slug %}">下一页<i class="fa fa-caret-square-o-right"></i></a>
                        {% endif %}
                    </div>
                </div>
            </div> <!-- end of pagination -->

{% endblock %}

templates/blog/postlist.html
{% load staticfiles %}
<!--//Content Area//-->
<div class="sp-content-area">

<!--//Post//-->
{% for item in posts %}
<article class="sp-post">
{% if item.post.image_link %}
    <div class="row" >
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <figure class="sp-thumb-container">
                <a href="single.html"><img src="{{ item.post.image_link }}" alt="Cannot load"></a>
            </figure>
        </div>
    </div>
{% endif %}
    <div class="row" >
        <div class="sp-post-content">
            <div class="sp-container">
                <div class="sp-post-desc">
                    <header class="sp-post-header">
                        <div class="sp-meta">
                            <span><a href="{% url 'blog:category' item.category.slug %}">{{ item.category }}</a></span> 
                            <span>{{ item.post.publish_date }}/span>
                        </div>
                        <h2 class="sp-post-title"><a href="{% url 'blog:single_post' item.category item.post.slug %}">{{ item.post.title }}</a></h2>
                            <div class="sp-post-info sp-clearfix">
                                <div class="sp-post-meta">
                                    <img class="sp-avatar" src="http://7xo4sa.com1.z0.glb.clouddn.com/owl.jpg" alt="">
                                        <p class="sp-author-name"><i class="fa fa-pencil"></i> by:<a href="/about.html">{{ item.post.author }}</a></p>
                                    <p class="sp-comment-count"> <i class="fa fa-tripadvisor"></i> views: {{ item.post.views }} </p>
                                    <hr class="sp-separator">
                                </div>
                                <div class="sp-share-this">
                                    <p class="sp-meta-title"> FollowMe:</p>
                                    <p class="sp-share-list">
                                    <a class="facebook" href="#" data-toggle="tooltip" data-replacement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
                                    <a class="weixin" href="#" data-toggle="tooltip" data-replacement="top" title="Weixin"><i class="fa fa-weixin"></i></a>
                                    <a class="mail" href="#" data-toggle="tooltip" data-replacement="top" title="Gmail"><i class="fa fa-envelope"></i></a>
                                    <a class="github" href="#" data-toggle="tooltip" data-replacement="top" title="Github"><i class="fa fa-github"></i></a>
                                    </p>
                                </div>
                            </div>
                    </header>
                <div class="sp-entry-content">
                    <p>{{ item.post.abstract }}</p>
                    <p>...</p>
                </div>
                <a class="sp-more button button-default" href="{% url 'blog:single_post' item.category.slug item.post.slug %}">Read More</a>
            </div>
        </div>
    </div>
</article> <!--//End Post-->
{% endfor %}

</div>

<!-- 实现分页显示 -->
<div class="sp-pagination">
    <div class="sp-container">
        <div class="sp-pagination-inner sp-clearfix">

            {% if posts.has_previous %}
                <a class="sp-prev" href="?page={{ posts.previous_page_number }}"><i class="fa fa-caret-square-o-left"></i> 上一页</a>
            {% endif %}

            <div class="sp-category"> <!-- Borrow the css format from the post.html -->
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            </div>

            {% if posts.has_next %}
                <a class="sp-next" href="?page={{ posts.next_page_number }}">下一页 <i class="fa fa-caret-square-o-right"></i></a>
            {% endif %}

        </div>
    </div>
</div><!-- End of the pagination -->

templates/blog/tags.html
{% extends 'blog/blog_base.html' %}       
{% load staticfiles %}
{% block update %}
<!-- Main Content -->
<div class="container"><!-- Override the css of the container in bootstrap -->
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <h1 class="category-name"><i class="fa-icon fa fa-cubes fa-2x"></i>Tag: {{ tag.name }}</h1>
            <!-- 打印对应的文章信息 -->
            {% if tag %}
                {% if posts %}
                    {% for bundle in posts %}
                        <div class="row">
                    <div class="col-xs-4 col-sm-4">
                        <img src="http://7xo4sa.com1.z0.glb.clouddn.com/owl.jpg" class="infor img-circle" alt="Loading..." style="width: 100px;  height: 100px;" />
                        <span class="infor"><i class="fa fa-calendar-check-o fa-2x"></i> 发表时间：2014-12-02 </span>
                    </div>
                    <div class ="col-xs-8 col-sm-6">
                        <a class="post-title" href="{% url 'blog:single_post' bundle.category  bundle.post.slug %}" data-toggle="tooltip" data-placement="top" title="点击查看该文章～" >    {{ bundle.post.title }} </a>
                        <div class="blog-infor pull right">
                            <span><i class="fa fa-tags"></i> 标签: 
                                {% for each_tag in bundle.tags %}
                                    <span><a href="{% url 'blog:tags' each_tag.slug %}"> {{ each_tag.name }} |</a></span>
                                {% endfor %}
                            </span>
                            <span><i class="fa fa-folder"></i>  分类: <a href="{% url 'blog:category' bundle.category.slug %}">{{ bundle.category.name }}</a></span>
                        </div>
                    </div>
                    </div>
                    <p align="right">
                        <span><i class="fa fa-eye"></i> 阅读<span class="badge">{{ bundle.post.views }} </span>
                        <span><i class="fa fa-thumbs-up"></i> 赞<span class="badge">{{ bundle.post.likes }} </span>
                        <span><i class="fa fa-comments"></i> 评论<span class="badge"> 0 </span> <!-- the comment function is not implemented yet -->
                  </p>
                  <hr/>
                    {% endfor %}
                {% endif %}
            {% endif %}
    <!-- -Doing some significant change-->
           
            <!-- 实现分页显示 -->
            <div class="pagination">
                <span class="step-links">
                        {% if posts.has_previous %}
                            <a class="sp-prev" href="?page={{ posts.previous_page_number }}"><i class="fa fa-caret-square-o-left"></i> 上一页</a>
                        {% endif %}

                        <span class="current">
                            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                        </span>

                        {% if posts.has_next %}
                            <a class="sp-next" href="?page={{ posts.next_page_number }}">下一页 <i class="fa fa-caret-square-o-right"></i></a>
                        {% endif %}
                </span>
            </div><!-- End of the pagination -->
        </div> 
    </div> <!-- End of the container -->
</div>
{% endblock %}