myWeb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
import blog, home

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myWeb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'grappelli/', include('grappelli.urls')),
    url(r'^$', 'home.views.home', name="home"),  # The website homepage
    url(r'^home/', include('home.urls', namespace="home")), # The website homepage
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^vpn/', include('vpn.urls', namespace="vpn")),
    url(r'^admin/', include(admin.site.urls)),
)
if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Any pattern states that for any file requested with a URL starting with media/, the request will be passed to the django.views.static view.
# This views handles the dispatching of upload media files for you.
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}),
    )

vpn/urls.py
from django.conf.urls import patterns, url
from vpn import views


urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^register/', views.register, name='register'),
        url(r'^logout/', views.user_logout, name='logout'),
        url(r'^login/', views.user_login, name='login'),
    )

VPN/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50)
    email = model.EmailField()
    password = models.CharField(max_length=50)

    FEMALE = 'F'
    MALE = 'M'
    SEX_CHOICE = ((FEMALE, 'female'),(MALE, 'male'))
    sex = models.CharField(max_length=1, choice=SEX_CHOICE, defalt=FEMALE,blank=True)

    joined_date = models.DateTimeField(editable=False)
    last_login = models.DateTimeField()
    user_level = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
    """On save, update timestamps """
        if not self.user_id:
            self.created = timezone.now()
        self.last_login = timezone.now()
        return super(User, self).save(*args, **kwargs)

vpn/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    FEMALE = 'F'
    MALE = 'M'
    SEX_CHOICE = ((FEMALE, 'female'),(MALE, 'male'))
    sex = models.CharField(max_length=1, choices=SEX_CHOICE,blank=True)

    website = models.URLField(blank=True)
    last_login = models.DateTimeField(auto_now=True)
# An integer stands for the level of the user(potnetial buyer)
    user_level = models.PositiveIntegerField(default=0)
# Email validation (proved or not)
    status = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.user.username

vpn/forms.py
from vpn.models import UserProfile
from django.contrib.auth.models import User
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class UserForm(forms.ModelForm):
    password = forms.CharField(max_length=50, help_text="不少于六位密码", widget=forms.PasswordInput)
    confirm_password = forms.CharField(max_length=50, help_text="重复上面的密码", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'confirm_password')
        # Provide an association between the ModelForm and a model
        labels = {
                    #'username': ('User'),
                }
        help_texts = {
                    'email':('例如: wnagyi163@163.com'),
                    'username':('少于30个字符,只使用数字,字母 @/.+/-/_'),
                }
        error_messages = {
                    'username':{
                        'required':('用户名必须填写'),  
                        'invalid':('用户名已经存在')
                        },
                    'email':{
                        'invalid': ('邮件格式不对'),
                        'required':('邮件必须填写'),
                        },
                    'password':{
                        'required':('密码必须填写')
                        },
                    'confirm_password':{
                        'required':('必须填写')
                        },
                }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        #self.helper.form_method = 'post'
# Action on calling the register view again, do the data validation 
        #self.helper.form_action = ''
        self.helper.form_tag = False
        

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get('password')
        if password and len(password) < 6:
            self.add_error('password', '密码长度必须超过六位')

        if cleaned_data.get('password') != cleaned_data.get('confirm_password'):
            self.add_error('confirm_password', '两次密码不一致')
            #raise forms.ValidationError(('两次密码不一致'), code="invalid")
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('sex',)
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))
        self.helper.form_tag = False

#class LoginForm(forms.ModelForm):
   # username = models.CharField(max_length=30, required=True)
   # password = forms.CharField(max_length=50, widget=forms.PasswordInput, required=True)
   # class = Meta:
   #     field = ('username', 'password',)
    #def __init__(self, *args, **kwargs):
    #    super(LoginForm, self).__init__(*args, **kwargs)
    #    self.helper = FormHelper()
    #    self.helper.method = 'post'
    #    self.helper.action = ''

vpn/views.py
from django.shortcuts import render
from vpn.models import User
from vpn.forms import UserForm, UserProfileForm
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
# Create your views here.

# The home page of the VPN  
# if the request is a POST, we process form data, if it is a GET, we show the form
def register(request):
    redirect_to = request.REQUEST.get('next', '')
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

# Have we benn provided with a valid form??
        if user_form.is_valid() and profile_form.is_valid():
# Save the new User to the database 
            user = user_form.save(commit=True)
            user_id = user.pk   # the form.pk also works
# encry the password
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
# Adding the OneToOne relationship between user and userprofile
            profile.user = user
            profile.save()
# Once successfully registered
#request.session['user_id'] = user_id
#request.session['username'] = request.POST['username']
# How to use if request.session.has_key('user_id') user_id = request.session.get('user_id')
            #messages.info(request, "Thanks for registering. You are now logged in.")
            new_user = authenticate(username=request.POST['username'], password=request.POST['password'])
            #user = authenticate(username=user.username, password=user.password)
            if new_user:
                if new_user.is_active:
                    login(request, new_user)
                    #login(request, user)
                    print("You got here")
                    #messages.success(request, 'Profile details updated.')
                    return HttpResponseRedirect(redirect_to)
                else:
                    return HttpResponse("Your Rango account is disabled.")
            else:
                return HttpResponse("Something wrong with the register process")
        else: print(user_form.errors, profile_form.errors)
    else:
# If the request was not POST, display the form to enter details 
        user_form = UserForm()
        profile_form = UserProfileForm()
# Bad from, no form supplied(form details)
# Render the form with error message(if any
    return render(request, 'vpn/register.html', {'user_form': user_form, 'profile_form':profile_form})

def index(request):
    username = None
    user_id = None
    if request.session.has_key('user_id'):
        user_id = request.session.get('user_id')
        username = request.session.get('username')
    
    context_dict = {
                'username': username, 
                'user_id': user_id,
            }
    return render(request, 'vpn/index.html', context_dict)

def user_logout(request):
   # if request.session.has_key('user_id'):
   #     request.session.modified = True
   #     del request.session['user_id']
   #     del request.session['username']
       # username = None
        #redirect_url = reverse(request.META.get('HTTP_REFERER'), args=['username'])
    logout(request)
# Return to the original page
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
# if we have a User object, the detail are correct, if None, no user with matching credentials was found
        if user:
           if user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            #print("Invalid login details:{0}, {1}".format(username, password))
            messages.error(request, "用户名、密码组合错误， 请重新尝试登录")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            #return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'vpn/index')

templates/vpn/errormessage.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %}"{% endif %}> 
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/vpn/index.html
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block title %}
    VPN 
{% endblock %}

{% block custome_css %}
    <link href='{% static "vpn/css/index.css" %}' rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Validate if user logging in, different views -->
    {% if user.is_authenticated %}
        {% include 'vpn/signbar.html' %}
    {% else %}
        {% include 'vpn/navbar.html' %}
    {% endif %}

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Company 2014</p>
      </footer>
    </div> <!-- /container -->

{% endblock %}

{% block custome_js%}
{% endblock %}

templates/vpn/navbar.html
{% include 'vpn/errormessage.html' %}
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">EGG VPN</a>
        </div>
        <center>
            <div class="navbar-collapse collapse" id="navbar-main">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'home:home' %}">主页</a>
                    </li>
                    <li><a href="{% url 'blog:index' %}">博客</a>
                    </li>
                    <li><a href="#">联系我</a>
                    </li>
                </ul>
                <form id="login_form" class="navbar-form navbar-right" role="search" method="post" action="{% url 'vpn:login' %}">{% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" name="password" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-default">登录</button>
                <a href="/vpn/register/?next={{ request.path }}"><button type="button" class="btn btn-default">注册</button></a>
                </form>
            </div>
        </center>
    </div>
</div>

templates/vpn/register.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block custome_css %}
    <style>
        body {
          padding-top: 80px;
          padding-bottom: 40px;
          background-color: #eee;
          height: 100vh;
          background: url('{% static "vpn/images/signup.jpg" %}') no-repeat center center fixed; 
          -webkit-background-size: cover;
          -moz-background-size: cover;
          -o-background-size: cover;
          background-size: cover;
        }
    </style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-8 col-sm-6 col-md-4 col-xs-offset-2 col-sm-3 col-md-offset-4">
            <form action='' method="post">
                {% crispy user_form %}
                {% crispy profile_form %}
            </form>
        </div>
    </div>
{% endblock %}

templates/vpn/signbar.html
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'vpn:index' %}">EGG VPN</a>
        </div>
        <center>
            <div class="navbar-collapse collapse" id="navbar-main">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'home:home' %}">主页</a>
                    </li>
                    <li><a href="{% url 'blog:index' %}">博客</a>
                    </li>
                    <li><a href="#">联系我</a>
                    </li>
                    <li class="navbar-right dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">用户中心: {{ user.username }}<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">完善个人信息</a></li>
                            <li><a href="#">订阅服务</a></li>
                            <li class="divider"></li>
                            <li><a href="#">购买记录</a></li>
                            <li><a href="#">订单</a></li>
                        </ul>
                    </li>
                </ul>
                <a href="{% url 'vpn:logout' %}"><button type="button" class="navbar-right btn btn-default navbar-btn">注销</button></a>
        </center>
    </div>
</div>